### ISSUE TITLE
Interface corrupted on Ubuntu 20.04

### ISSUE THREAD

**Issue by michaelarnauts** [amanharwara/altus#70] opened 2020-06-25 08:20 UTC
**Describe the bug**

There seems to be an UI issue. I can't find anything related in the buglist.
```
$ ./Altus-3.12.0.AppImage
(node:1787030) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at /tmp/.mount_Altus-Tz5gU0/resources/app.asar/windows/util/generateTheme.js:49:19
    at Renderer.render (/tmp/.mount_Altus-Tz5gU0/resources/app.asar/node_modules/stylus/lib/renderer.js:107:12)
    at Function.exports.render (/tmp/.mount_Altus-Tz5gU0/resources/app.asar/node_modules/stylus/lib/stylus.js:82:37)
    at generateTheme (/tmp/.mount_Altus-Tz5gU0/resources/app.asar/windows/util/generateTheme.js:48:10)
    at /tmp/.mount_Altus-Tz5gU0/resources/app.asar/index.js:66:24
(node:1787030) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at /tmp/.mount_Altus-Tz5gU0/resources/app.asar/windows/util/generateTheme.js:49:19
    at Renderer.render (/tmp/.mount_Altus-Tz5gU0/resources/app.asar/node_modules/stylus/lib/renderer.js:107:12)
    at Function.exports.render (/tmp/.mount_Altus-Tz5gU0/resources/app.asar/node_modules/stylus/lib/stylus.js:82:37)
    at generateTheme (/tmp/.mount_Altus-Tz5gU0/resources/app.asar/windows/util/generateTheme.js:48:10)
    at /tmp/.mount_Altus-Tz5gU0/resources/app.asar/index.js:66:24
(node:1787030) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1787030) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1787030) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1787030) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
I just executed it.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1193779/85682935-0bc17480-b6cd-11ea-95c3-0d27c8f1775b.png)

**Information:**
 - OS: Ubuntu 20.04
 - Altus Version: 3.12.0

**Additional context**

I'm not sure if node is also embedded in the AppImage, but I have node v10.21.0 installed.

**Comment by michaelarnauts** [comment] 2020-06-25 09:08
Can you tell me what version of GNOME or GTK you are using on your machine. I'm using GNOME 3.36.2 with GTK 3.24.

**Comment by amanharwara** [comment] 2020-06-25 09:22
I use KDE Plasma as the desktop environment and don't have GTK installed either.

Also, as far as I know, nothing in my app really depends on GTK so I don't think that would change anything.

**Comment by CollinAlpert** [comment] 2020-07-04 21:14
Same problem with me. I am using Fedora 32. Using version 3.11.1 works fine.

**Comment by amanharwara** [comment] 2020-07-05 12:06
For some reason it works just fine on Manjaro. At least on my machine, it does.

**Comment by CollinAlpert** [comment] 2020-07-05 12:38
I guess I'll just stick with version 3.11.1 for now and then wait until v4.0 is released :)

**Comment by amanharwara** [comment] 2020-07-10 18:00
@CollinAlpert Can you send the terminal output for the problematic version? I read through the terminal output OP has posted and want to see if that really is the issue that's causing the problem.

**Comment by CollinAlpert** [comment] 2020-07-10 18:05
My terminal output is the same as OPs. I can send it when I get the chance, but I get the same error.

**Comment by amanharwara** [comment] 2020-07-14 07:17
I found a fix for this issue but there's a weird thing happening... The app works correctly when I'm developing it but as soon as I package it and test it, it stops working.

**Comment by CollinAlpert** [comment] 2020-07-14 09:13
Thanks for the update, it definitely looks like a weird bug!

**Comment by amanharwara** [comment] 2020-07-14 13:18
So it looks like it's not a problem with Linux itself but rather the packaging; at least from what I can tell.
I've managed to generate an AppImage that works as intended, but I'm not sure what the dependency situation might be.
I'll release it and then you can let me know if it causes any issue.

**Comment by amanharwara** [comment] 2020-07-14 14:09
Please test out [v3.2.1](https://github.com/amanharwara/altus/releases/tag/3.12.1) and let me know.
Sorry for the ridiculous download size but this alternative packaging is what seems to have worked.

**Comment by CollinAlpert** [comment] 2020-07-16 17:42
Works fine for me!

**Comment by insign** [comment] 2020-07-20 20:27
It happened to me too. Since I`m using Windows now, can test again, but few weeks ago I couldn't use.

**Comment by amanharwara** [comment] 2020-07-29 12:16
Closing since there's no response from OP 2 weeks after releasing the fix.

**Closed by amanharwara** 2020-07-29 12:16 UTC
Labels: bug, waiting-for-response
