### ISSUE TITLE
Can't launch on Mac 11.1 Big Sur

### ISSUE THREAD

**Issue by saiqulhaq** [amanharwara/altus#111] opened 2021-01-03 13:48 UTC
**Describe the bug**
I just downloaded your app from `releases` page, latest version

**To Reproduce**

1. Just open
2. Mac will prevent you to open this app
3. Allow mac to open it, on `security` setting
4. open app again, then you will got this

<img width="280" alt="Screen Shot 2021-01-03 at 20 43 55" src="https://user-images.githubusercontent.com/1275215/103480134-01fb9500-4e05-11eb-94fe-d8b0d7663642.png">

**Comment by amanharwara** [comment] 2021-01-03 15:34
Can you try if [v3.23.0](https://github.com/amanharwara/altus/releases/tag/3.23.0) works for you?

**Comment by saiqulhaq** [comment] 2021-01-03 19:09
for earlier versions, it works, I can fill all fields
but then it does nothing when I click `add tab` button


On January 4, 2021, Dominik Sander <notifications@github.com> wrote:
> Can you try if v3.23.0
> <https://github.com/amanharwara/altus/releases/tag/3.23.0> works for

> you?
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/amanharwara/altus/issues/111#issuecomment-
753634807>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAJXKT2S5RNXQBWWJKEUEYLSYCFA3ANCNFSM4VR4I74Q>.

**Comment by amanharwara** [comment] 2021-01-19 07:52
Can you check & see if [v4.0-beta1](https://github.com/amanharwara/altus/releases/tag/4.0.0-beta1) works for you?

**Comment by rebelcode-xr** [comment] 2021-01-27 00:44
I had the same problem and I can confirm that **v4.0 beta 3** works on Big Sur! ;)

**Comment by amanharwara** [comment] 2021-01-28 10:09
Closing since this fixed in v4.0+

**Closed by amanharwara** 2021-01-28 10:09 UTC
Labels: bug
